name: Publish
on:
  push:
jobs:
  generate-values:
    runs-on: ubuntu-latest
    outputs:
      values: ${{ steps.generate_values.outputs.values }}  # Output from this job
    steps:
      - name: Generate Values
        id: generate_values
        run: |
          aaa=true
          bbb=true
          ccc=true

          # Initialize an empty array
          values=()

          # Check each variable and add to the array if true
          if [ "$aaa" = true ]; then
              values+=("a") # Add "a" if aaa is true
          fi
          if [ "$bbb" = true ]; then
              values+=("b") # Add "b" if bbb is true
          fi
          if [ "$ccc" = true ]; then
              values+=("c") # Add "c" if ccc is true
          fi

          printf -v joined '"%s", ' "${values[@]}"
          joined="${joined%, }"  # Remove the trailing comma and space
          result="values=[$joined]"  # Format the final string

          echo "::set-output name=values::$joined" 
  build:
    needs: generate-values
    runs-on: ubuntu-latest
    strategy:
      matrix:
        value: ${{fromJSON(needs.setup.outputs.matrix)}}
    steps:
      - run: |
          echo "${{ matrix.value }}"
