name: Test Project
on: push
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - name: printing
        run:  |
          echo "OUTBOX_TYPE=S3" >> $GITHUB_ENV
          echo "S3_OUT_ENDPOINT=localhost" >> $GITHUB_ENV
          echo "S3_OUT_PORT=9000" >> $GITHUB_ENV
          echo "S3_OUT_SECURE=false" >> $GITHUB_ENV
          echo "$GITHUB_ENV"
